#!/usr/bin/env ruby

# TODO read each character in the file as a stream, rather than parsing the
#  whole String and splitting it

def parse(filename)
  instructions = open filename
  instructions.read.split(//)
end

def count(instructions)
  floor = 0

  if instructions.respond_to?("each")
    instructions.each do |i|
      if i == '('
        floor += 1
      elsif i == ')'
        floor -= 1
      end
    end
  end
  floor
end

if __FILE__ == $0
  instructions = parse(ARGV.first)
  puts count instructions
end
